export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
// export const DECREASE_COUNTER = 'DECREASE_COUNTER';
// export const RESET_COUNTER = 'RESET_COUNTER';
// export const SET_COUNTER = 'SET_COUNTER';
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const ERROR_PRODUCTS = "ERROR_PRODUCTS";
