export const FILTER_BY_HOME = "FILTER_BY_HOME";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const FILTER_BY_ROOM = "FILTER_BY_ROOM";

export const LOADING_FILTER_DATA = "LOADING_FILTER_DATA";
export const ERROR_FILTER_DATA = "ERROR_FILTER_DATA";
