export const FILTER_BY_HOME = "FILTER_BY_HOME";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const FILTER_BY_ROOM = "FILTER_BY_ROOM";
export const FILTER_BY_BATH = "FILTER_BY_BATH";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const FILTER_BY_CONDITION = "FILTER_BY_CONDITION";
export const FILTER_BY_OTHER = "FILTER_BY_OTHER";
export const FILTER_BY_DATE = "FILTER_BY_DATE";

export const LOADING_FILTER_DATA = "LOADING_FILTER_DATA";
export const ERROR_FILTER_DATA = "ERROR_FILTER_DATA";
